// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF1JX00mKNrwlTT-7vR7O56XU8VEN6XlU',
    appId: '1:87234460701:web:70d0fb43419e66b2689af4',
    messagingSenderId: '87234460701',
    projectId: 'fir-web-learn-8bfb5',
    authDomain: 'fir-web-learn-8bfb5.firebaseapp.com',
    databaseURL: 'https://fir-web-learn-8bfb5.firebaseio.com',
    storageBucket: 'fir-web-learn-8bfb5.appspot.com',
    measurementId: 'G-FN81VFP3NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfFqVVvSdan4qfumPvACBMmbQaPZPjWNk',
    appId: '1:87234460701:android:c15e1b1b4f4ea493689af4',
    messagingSenderId: '87234460701',
    projectId: 'fir-web-learn-8bfb5',
    databaseURL: 'https://fir-web-learn-8bfb5.firebaseio.com',
    storageBucket: 'fir-web-learn-8bfb5.appspot.com',
  );
}
